### ISSUE TITLE
screenshot of the appimage

### ISSUE THREAD

**Issue by pirate486743186** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#34]
I think you could have chosen a better screenshot for the appimage.
https://appimage.github.io/Waterfox_Classic/

**Comment by hawkeye116477** [comment]
I didn't choose screenshot for AppImage. It was automaticaly taken by some tool which uses AppImage format author. That tool apparently doesn't have access to the Internet, so that's why that looks like. 

I wanted to submit better screenshot as Pull Request, but he told me that I must to place AppStream metainfo file with URLs to it, but problem is that then OBS reports me that it can't verify metadata, because of no Internet access, then I told to him that I have that problem, then he told me about some workaround, but unfortunately it won't worked for me. See https://github.com/AppImage/appimage.github.io/pull/1704. I'll look for it now, maybe something changed, but I doubt it, they even didn't fixed updates through right click, it still says that verification failed.

**Comment by hawkeye116477** [comment]
@pirate486743186 I tried again and there are same problems as on https://github.com/AppImage/AppImageKit/issues/603, which is opened from 2017 and still not solved, so I assume that problem with screenshot could be forever.

**Comment by pirate486743186** [comment]
isn't this a bug in OBS?

**Comment by hawkeye116477** [comment]
In case of no internet connection, then it's normal that during a build in OBS there is no internet connection. In case of that second bug, it's probably something broken on side of AppImageKit.
